(* open Object *)
(**)
(* (* module Environment = struct  *) *)
(* type t = (string, Object.t) Hashtbl.t *)
(* (* type t = (string, Object.t) Hashtbl.t *) *)
(**)
(* let new_env () = Hashtbl.create 1;; *)
(**)
(* let get env key = Hashtbl.find_opt env key;; *)
(**)
(* let set env key value = Hashtbl.replace env key value;; *)
(**)
(* let add env key value = Hashtbl.add env key value;; *)
(**)
(* let remove env key = Hashtbl.remove env key;; *)
(* (* end *) *)
